name: limmbo-py3
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- filechunkio=1.6=py35_0
- ftputil=3.2=py35_0
- pyasn1-modules=0.0.5=py35_0
- pygraphviz=1.3.1=py35_0
- pysftp=0.2.9=py35_0
- rsa=3.1.4=py35_0
- snakemake=5.1.5=py35_0
- urllib3=1.12=py35_0
- aioeasywebdav=2.2.0=py35_0
- aiohttp=3.1.3=py35_0
- appdirs=1.4.3=py_1
- asciitree=0.3.3=py35_1
- asn1crypto=0.24.0=py35_0
- async-timeout=2.0.1=py35_0
- attrs=18.1.0=py_1
- bokeh=0.12.16=py35_0
- boto3=1.7.45=py_0
- botocore=1.10.45=py_0
- brent-search=1.0.32=py35_0
- cachetools=2.0.1=py_0
- cffi=1.11.5=py35_0
- chardet=3.0.4=py35_0
- click=6.7=py_1
- cloudpickle=0.5.3=py_0
- configargparse=0.12.0=py35_0
- cryptography=2.2.1=py35_0
- cycler=0.10.0=py35_0
- cytoolz=0.9.0.1=py35_0
- dask=0.18.0=py_0
- dask-core=0.18.0=py_0
- dbus=1.13.0=h3a4f0e9_0
- decorator=4.3.0=py_0
- distributed=1.22.0=py35_0
- docutils=0.14=py35_0
- dropbox=7.3.1=py35_0
- expat=2.2.5=0
- fontconfig=2.13.0=0
- freetype=2.8.1=0
- glimix-core=1.2.26=py35_0
- google-auth=1.2.1=py_0
- google-auth-httplib2=0.0.2=py35_0
- google-cloud-core=0.24.1=py35_0
- google-cloud-storage=1.1.1=py35_0
- google-resumable-media=0.0.2=py35_0
- googleapis-common-protos=1.5.3=py35_0
- graphite2=1.3.11=hfc679d8_0
- graphviz=2.38.0=7
- h5py=2.8.0=py35hb794570_1
- hcephes=0.2.3=1
- hdf5=1.10.2=0
- heapdict=1.0.0=py35_0
- httplib2=0.11.1=py35_0
- icu=58.2=0
- idna=2.7=py35_0
- idna_ssl=1.0.0=0
- jinja2=2.10=py35_0
- jmespath=0.9.3=py35_0
- joblib=0.11=py35_0
- jpeg=9b=2
- jsonschema=2.6.0=py35_1
- kiwisolver=1.0.1=py35_1
- libiconv=1.15=0
- libpng=1.6.34=0
- libprotobuf=3.5.2=0
- libtiff=4.0.9=he6b73bb_0
- libtool=2.4.6=0
- libuuid=1.0.3=1
- libxcb=1.13=0
- libxml2=2.9.8=0
- liknorm=1.3.11=0
- liknorm-py=1.0.12=py35_0
- limix=1.0.17=py35_0
- limix-core=1.0.2=py35_1
- limix-legacy=0.8.12=np114py35_3
- llvmlite=0.23.0=py35_1
- locket=0.2.0=py35_1
- markupsafe=1.0=py35_0
- matplotlib=2.2.2=py35_1
- mkl_fft=1.0.2=py35_0
- mkl_random=1.0.1=py35_0
- msgpack-python=0.5.6=py35h2d50403_2
- multidict=4.3.1=py35_0
- ncephes=1.0.40=py35_0
- ndarray-listener=1.1.1=py35_0
- networkx=2.1=py35_0
- numba=0.38.1=py35_0
- numpy-sugar=1.2.5=py35_0
- optimix=1.2.23=py35_1
- packaging=17.1=py_0
- pandas=0.23.1=py35_0
- pandas-plink=1.2.25=py35_0
- paramiko=2.4.1=py35_0
- partd=0.3.8=py35_0
- pcre=8.41=1
- pixman=0.34.0=2
- prettytable=0.7.2=py35_1
- protobuf=3.5.2=py35_0
- psutil=5.4.6=py35_0
- pyasn1=0.4.3=py_0
- pycparser=2.18=py35_0
- pynacl=1.1.2=py35_0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_5
- python-dateutil=2.7.3=py_0
- python-irodsclient=0.7.0=py_0
- pytz=2018.4=py_0
- pyyaml=3.12=py35_1
- ratelimiter=1.2.0=py35_0
- requests=2.13.0=py35_0
- s3transfer=0.1.13=py35_0
- scipy-sugar=1.0.7=py35_0
- sip=4.18=py35_1
- six=1.11.0=py35_1
- sortedcontainers=2.0.3=py35_0
- tblib=1.3.2=py35_0
- toolz=0.9.0=py_0
- tornado=5.0.2=py35_0
- tqdm=4.23.4=py_0
- wrapt=1.10.11=py35_0
- xmlrunner=1.7.7=py_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- yaml=0.1.7=0
- yarl=1.2.6=py35h470a237_0
- zict=0.1.3=py_0
- bcrypt=3.1.4=py35ha35c455_0
- ca-certificates=2018.03.07=0
- cairo=1.14.12=h77bcde2_0
- certifi=2018.4.16=py35_0
- datrie=0.7.1=py35_0
- glib=2.53.6=h5d9569c_2
- gst-plugins-base=1.12.4=h33fb286_0
- gstreamer=1.12.4=hb53b477_0
- harfbuzz=1.7.6=hc5b324e_0
- intel-openmp=2018.0.3=0
- libedit=3.1.20170329=h6b74fdf_2
- libffi=3.2.1=hd88cf55_4
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=7.2.0=hdf63c60_3
- libgfortran=3.0.0=1
- libgfortran-ng=7.2.0=hdf63c60_3
- libstdcxx-ng=7.2.0=hdf63c60_3
- mkl=2018.0.3=1
- ncurses=6.1=hf484d3e_0
- numpy=1.14.2=py35hdbf6ddf_1
- openssl=1.0.2o=h20670df_0
- pango=1.40.11=h8191d47_0
- pip=10.0.1=py35_0
- python=3.5.5=hc3d631a_4
- qt=5.6.2=hd25b39d_14
- readline=7.0=ha6073c6_4
- scikit-learn=0.19.1=py35hbf1f462_0
- scipy=1.1.0=py35hfc37229_0
- setuptools=39.2.0=py35_0
- sqlite=3.24.0=h84994c4_0
- tk=8.6.7=hc745277_3
- wheel=0.31.1=py35_0
- xz=5.2.4=h14c3975_4
- zlib=1.2.11=ha838bed_2
- pip:
  - alabaster==0.7.11
  - apipkg==1.4
  - atomicwrites==1.1.5
  - babel==2.6.0
  - bottleneck==1.2.1
  - cython==0.28.3
  - dill==0.2.8.2
  - execnet==1.5.0
  - idna-ssl==1.0.0
  - imagesize==1.0.0
  - mkl-fft==1.0.2
  - mkl-random==1.0.1
  - more-itertools==4.2.0
  - msgpack==0.5.6
  - multiprocess==0.70.6.1
  - pathos==0.2.2
  - pep8==1.7.1
  - pluggy==0.6.0
  - pox==0.2.4
  - ppft==1.6.4.8
  - py==1.5.3
  - pyaml==17.12.1
  - pygments==2.2.0
  - pytest==3.6.2
  - pytest-cache==1.0
  - pytest-pep8==1.0.6
  - pytest-runner==4.2
  - snowballstemmer==1.2.1
  - sphinx==1.7.5
  - sphinx-rtd-theme==0.4.0
  - sphinxcontrib-websupport==1.1.0

